SELECT A.EMP_NO, MAX(A.JOB_GRADE) JOB_GRADE, MAX(A.EMP_NM) EMP_NM, SUM(B.BONUS_AMT) BONUS_AMT,
       MAX(SUM(B.BONUS_AMT)) OVER(PARTITION BY MAX(A.JOB_GRADE)) MAX_BONUS_AMT
  FROM EMP A INNER JOIN EMP_BONUS B 
       ON A.EMP_NO = B.EMP_NO AND B.BONUS_YYYY = '2019' AND B.BONUS_MM = '04'
GROUP BY A.EMP_NO; 

SELECT A.EMP_NO, A.EMP_NM, A.JOB_GRADE, A.BONUS_AMT,
--       MAX(A.BONUS_AMT) OVER(PARTITION BY A.JOB_GRADE) MAX_BONUS_AMT,
       RANK() OVER(PARTITION BY A.JOB_GRADE ORDER BY A.BONUS_AMT DESC) JOB_RANK,
       SUM(A.BONUS_AMT) OVER(PARTITION BY A.JOB_GRADE ORDER BY A.BONUS_AMT DESC RANGE UNBOUNDED PRECEDING) JOB_TOT,
       SUM(A.BONUS_AMT) OVER(ORDER BY A.JOB_GRADE, A.BONUS_AMT DESC RANGE UNBOUNDED PRECEDING) GLO_TOT
  FROM ( SELECT A.EMP_NO, MAX(A.JOB_GRADE) JOB_GRADE, MAX(A.EMP_NM) EMP_NM, SUM(B.BONUS_AMT) BONUS_AMT
           FROM EMP A INNER JOIN EMP_BONUS B 
               ON A.EMP_NO = B.EMP_NO AND B.BONUS_YYYY = '2019' AND B.BONUS_MM = '04'
        GROUP BY A.EMP_NO ) A;