DECLARE
    V_CUST_ID VARCHAR2(50);
    V_CUST_NM VARCHAR2(50);
    CURSOR C_CUSTOMER IS
        SELECT CUST_ID, CUST_NM
          FROM CUSTOMER;
BEGIN
    OPEN C_CUSTOMER;
    LOOP
        FETCH C_CUSTOMER INTO V_CUST_ID, V_CUST_NM;
        IF V_CUST_ID = '2016000001' THEN
            DBMS_OUTPUT.PUT_LINE('IF안 문장 실행'||V_CUST_NM);
        ELSIF V_CUST_ID = '2016000002' THEN
            DBMS_OUTPUT.PUT_LINE('ELIF안 문장 실행'||V_CUST_NM);
        END IF;
        EXIT WHEN C_CUSTOMER%NOTFOUND;
    END LOOP;    
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE P_UPDATE_BASIC_PAY
( P_JOB_GRADE IN EMP_PAY.JOB_GRADE%TYPE
 ,P_JOB_YEAR IN EMP_PAY.JOB_YEAR%TYPE )
IS
BEGIN
    UPDATE EMP_PAY SET BASIC_PAY = BASIC_PAY*1.1
     WHERE JOB_GRADE = P_JOB_GRADE
       AND JOB_YEAR = P_JOB_YEAR;

    COMMIT;   
    
EXCEPTION 
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);    
        ROLLBACK;        
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

EXECUTE P_UPDATE_BASIC_PAY('01', '2019');
