DECLARE
    CURSOR C_CUSTOMER IS
        SELECT A.CUST_ID, A.CUST_NM, A.ADDRESS, A.CEL_PHONE
          FROM CUSTOMER A
         WHERE A.CUST_ID = '2019' ;
    V_CUSTOMER_REC CUSTOMER%ROWTYPE;
    V_BOOK_REC BOOK%ROWTYPE;
BEGIN
    SELECT A.BOOK_ID, A.BOOK_NM
      INTO V_BOOK_REC.BOOK_ID, V_BOOK_REC.BOOK_NM
      FROM BOOK A
     WHERE A.BOOK_ID = '0000000001' ;
    
    OPEN C_CUSTOMER;
    LOOP
        FETCH C_CUSTOMER INTO V_CUSTOMER_REC;
        EXIT WHEN C_CUSTOMER%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_CUSTOMER_REC.CUST_ID||V_CUSTOMER_REC.CUST_NM);
    END LOOP;
    CLOSE C_CUSTOMER;
     
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO_DATA_FOUND');
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('TOO_MANY_ROWS');
        DBMS_OUTPUT.PUT_LINE(SQLERRM);        
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

DECLARE
    CURSOR C_EMP_PAY IS
        SELECT A.JOB_GRADE, A.JOB_YEAR, A.BASIC_PAY
          FROM EMP_PAY A
        FOR UPDATE;
    V_EMP_PAY_REC EMP_PAY%ROWTYPE;      
BEGIN
    OPEN C_EMP_PAY;
    LOOP
        FETCH C_EMP_PAY INTO V_EMP_PAY_REC;
        EXIT WHEN C_EMP_PAY%NOTFOUND;

        UPDATE EMP_PAY SET BASIC_PAY = BASIC_PAY * 0.1
         WHERE CURRENT OF C_EMP_PAY;
         
    END LOOP;
    CLOSE C_EMP_PAY;
    COMMIT;
END;